name: uli-init
channels:
  - conda-forge
dependencies:
  - deepsmiles=1.0.1
  - ele=0.1.0
  - foyer=0.7.7
  - garnett=0.7.1
  - gsd=2.4.0
  - matplotlib
  - mdtraj=1.9.5
  - networkx=2.5
  - numpy=1.20.1
  - openbabel=3.1.1
  - oset=0.1.3
  - packmol=20.010
  - parmed=3.4.0
  - pip=21.0
  - pytest
  - pytest-cov
  - python=3.7
  - scipy=1.6.0
  - signac=1.6.0
  - signac-flow=0.12.0
  - pip:
      - git+https://github.com/chrisjonesBSU/mbuild.git@hoomd_sim
      - git+https://github.com/cmelab/uli-init.git@0.0.6
