name: polybinder 
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - foyer=0.11.0
  - freud=2.8.0
  - gsd=2.5.1
  - hoomd=*=*gpu*
  - mbuild=0.14.2
  - numpy=1.22
  - pip=22.0.4
  - pytest
  - pytest-cov
  - python=3.9
  - scipy=1.8.0
  - signac=1.7.0
  - signac-flow=0.18.1
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/chrisjonesBSU/polybinderCG.git@main
