name: uli-init
channels:
  - conda-forge
dependencies:
  - ele
  - foyer=0.7.7
  - gsd=2.4.0
  - mdtraj
  - numpy=1.20.1
  - packmol>=18
  - parmed>=3.4.0
  - pip=21.0
  - pytest
  - pytest-cov
  - python=3.7
  - rdkit=2021.03.1
  - scipy=1.6.0
  - signac=1.6.0
  - signac-flow=0.12.0
  - pip:
      - git+https://github.com/mosdef-hub/mbuild.git@master
      - git+https://github.com/cmelab/uli-init.git@0.2.0
